export interface StandardItem {
  code: string;
  title: string;
  cyclePhase: "PLANEAR" | "HACER" | "VERIFICAR" | "ACTUAR";
  weight7: number;   // Ponderación en matriz de 7 estándares
  weight21: number;  // Ponderación en matriz de 21 estándares
  weight60: number;  // Ponderación en matriz de 60 estándares
  description: string;
  minGroup: 7 | 21 | 60; // En qué grupo mínimo aparece
}

export const RESOLUCION_0312_STANDARDS: StandardItem[] = [
  // --- GRUPO DE 7 ESTÁNDARES (Empresas <= 10 trab., Riesgo I, II, III) ---
  {
    code: "1.1.1",
    title: "Responsable del SG-SST (Diseño y Asignación)",
    cyclePhase: "PLANEAR",
    weight7: 15,
    weight21: 5,
    weight60: 0.5,
    description: "Asignar una persona que cumpla con el perfil para el diseño del SG-SST (técnico, tecnólogo o profesional con licencia SST vigente y curso de 50 horas).",
    minGroup: 7,
  },
  {
    code: "1.1.2",
    title: "Afiliación al Sistema de Seguridad Social Integral",
    cyclePhase: "PLANEAR",
    weight7: 15,
    weight21: 5,
    weight60: 0.5,
    description: "Garantizar la afiliación de todos los trabajadores dependientes e independientes a Salud, Pensión y ARL según el nivel de riesgo.",
    minGroup: 7,
  },
  {
    code: "1.1.4",
    title: "Capacitación en SST",
    cyclePhase: "HACER",
    weight7: 15,
    weight21: 5,
    weight60: 2,
    description: "Elaborar y ejecutar un programa de capacitación en promoción y prevención que incluya a todos los trabajadores.",
    minGroup: 7,
  },
  {
    code: "2.1.1",
    title: "Plan Anual de Trabajo de SST",
    cyclePhase: "PLANEAR",
    weight7: 15,
    weight21: 5,
    weight60: 2,
    description: "Elaborar el Plan Anual de Trabajo del SG-SST firmado por el empleador, con metas, responsabilidades, recursos y cronograma.",
    minGroup: 7,
  },
  {
    code: "3.1.1",
    title: "Evaluaciones Médicas Ocupacionales",
    cyclePhase: "HACER",
    weight7: 15,
    weight21: 5,
    weight60: 1,
    description: "Realizar evaluaciones médicas de ingreso, periódicas y de egreso según el profesiograma y la Resolución 1843 de 2025.",
    minGroup: 7,
  },
  {
    code: "4.1.2",
    title: "Identificación de Peligros y Valoración de Riesgos",
    cyclePhase: "PLANEAR",
    weight7: 15,
    weight21: 5,
    weight60: 4,
    description: "Identificar peligros, evaluar y valorar los riesgos con participación de los trabajadores (aplicando metodología GTC 45).",
    minGroup: 7,
  },
  {
    code: "4.2.1",
    title: "Medidas de Prevención y Control frente a Peligros",
    cyclePhase: "HACER",
    weight7: 10,
    weight21: 5,
    weight60: 2.5,
    description: "Ejecutar actividades de prevención y control de peligros y riesgos conforme al orden de jerarquía de controles.",
    minGroup: 7,
  },

  // --- ADICIONALES PARA GRUPO DE 21 ESTÁNDARES (11 a 50 trab., Riesgo I, II, III) ---
  {
    code: "1.1.3",
    title: "Asignación de Recursos para el SG-SST",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 5,
    weight60: 0.5,
    description: "Definir y asignar los recursos financieros, técnicos y de personal necesarios para el diseño e implementación del SG-SST.",
    minGroup: 21,
  },
  {
    code: "1.1.6",
    title: "Conformación y Funcionamiento del COPASST / Vigía",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 5,
    weight60: 0.5,
    description: "Conformar y garantizar el funcionamiento del Comité Paritario de SST o designación del Vigía de Seguridad y Salud en el Trabajo.",
    minGroup: 21,
  },
  {
    code: "1.1.7",
    title: "Capacitación a Integrantes del COPASST / Vigía",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 5,
    weight60: 0.5,
    description: "Capacitar a los integrantes del COPASST o al Vigía para el cumplimiento efectivo de sus funciones legales.",
    minGroup: 21,
  },
  {
    code: "1.1.8",
    title: "Conformación y Funcionamiento del Comité de Convivencia",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 5,
    weight60: 0.5,
    description: "Conformar y asegurar las reuniones periódicas del Comité de Convivencia Laboral de acuerdo con la Resolución 652 de 2012.",
    minGroup: 21,
  },
  {
    code: "1.2.1",
    title: "Programa de Capacitación Anual en SST",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 5,
    weight60: 2,
    description: "Elaborar y documentar el Programa de Capacitación Anual en SST que incluya inducción, entrenamiento y temas prioritarios.",
    minGroup: 21,
  },
  {
    code: "1.2.2",
    title: "Inducción y Reinducción en SST",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 5,
    weight60: 1,
    description: "Realizar inducción y reinducción en SST a todos los trabajadores, contratistas y proveedores antes de iniciar labores.",
    minGroup: 21,
  },
  {
    code: "2.2.1",
    title: "Política de Seguridad y Salud en el Trabajo",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 5,
    weight60: 1,
    description: "Establecer por escrito la Política de SST, fechada y firmada por el representante legal, comunicada al COPASST y trabajadores.",
    minGroup: 21,
  },
  {
    code: "2.3.1",
    title: "Objetivos del SG-SST",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 5,
    weight60: 1,
    description: "Definir objetivos de SST medibles, cuantificables y coherentes con la política y las prioridades de la empresa.",
    minGroup: 21,
  },
  {
    code: "2.5.1",
    title: "Archivo y Retención Documental (20 Años)",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 5,
    weight60: 2,
    description: "Custodiar de forma digital o física los registros del SG-SST durante mínimo 20 años contados desde el cese de labores del trabajador.",
    minGroup: 21,
  },
  {
    code: "2.8.1",
    title: "Mecanismos de Comunicación y Auto-reporte",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 5,
    weight60: 1,
    description: "Disponer de mecanismos para recibir y responder las comunicaciones internas y externas sobre SST y auto-reporte de condiciones.",
    minGroup: 21,
  },
  {
    code: "3.1.2",
    title: "Perfiles y Descripción de Cargos con SST",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 5,
    weight60: 1,
    description: "Definir los perfiles de cargo con los requisitos mínimos de educación, formación y competencias en materia de SST.",
    minGroup: 21,
  },
  {
    code: "3.1.4",
    title: "Custodia de Historias Clínicas Ocupacionales",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 5,
    weight60: 1,
    description: "Garantizar la confidencialidad y custodia exclusiva de las evaluaciones médicas por médicos con licencia SST (Res. 1843/2025).",
    minGroup: 21,
  },
  {
    code: "4.2.3",
    title: "Plan de Prevención, Preparación y Respuesta ante Emergencias",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 5,
    weight60: 5,
    description: "Implementar un plan de prevención y respuesta ante emergencias con análisis de vulnerabilidad, brigadas y simulacros anuales.",
    minGroup: 21,
  },
  {
    code: "6.1.1",
    title: "Reporte e Investigación de Accidentes e Incidentes (15 Días Hábiles)",
    cyclePhase: "VERIFICAR",
    weight7: 0,
    weight21: 5,
    weight60: 2,
    description: "Reportar a ARL y EPS dentro de 2 días hábiles e investigar con el equipo investigador dentro de los 15 días hábiles (Res. 1401/2007).",
    minGroup: 21,
  },

  // --- COMPLEMENTARIOS PARA MATRIZ COMPLETA DE 60 ESTÁNDARES (>50 trab. o Riesgo IV, V) ---
  {
    code: "1.1.5",
    title: "Curso Virtual de 50 horas en SST del Responsable",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 0,
    weight60: 0.5,
    description: "Acreditar el certificado del curso de 50 horas del responsable del SG-SST o actualización de 20 horas según normatividad.",
    minGroup: 60,
  },
  {
    code: "2.4.1",
    title: "Evaluación Inicial del SG-SST",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 0,
    weight60: 1,
    description: "Realizar y documentar la evaluación inicial del SG-SST para identificar prioridades y plan de mejoramiento anual.",
    minGroup: 60,
  },
  {
    code: "2.6.1",
    title: "Rendición de Cuentas sobre el Desempeño en SST",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 0,
    weight60: 1,
    description: "Rendir cuentas a todos los niveles de la empresa al menos una vez al año sobre la gestión y resultados del SG-SST.",
    minGroup: 60,
  },
  {
    code: "2.7.1",
    title: "Matriz Legal de SST Actualizada",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 0,
    weight60: 2,
    description: "Elaborar y mantener actualizada la matriz de requisitos legales aplicables a la actividad económica y riesgos de la empresa.",
    minGroup: 60,
  },
  {
    code: "2.9.1",
    title: "Gestión de Proveedores y Contratistas en SST",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 1,
    description: "Garantizar que contratistas y proveedores cumplan con las normas de seguridad y afiliaciones a seguridad social integral.",
    minGroup: 60,
  },
  {
    code: "2.10.1",
    title: "Gestión del Cambio en Procesos y Maquinaria",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 1,
    description: "Disponer de un procedimiento para evaluar el impacto sobre la SST ante cambios internos o externos en la organización.",
    minGroup: 60,
  },
  {
    code: "2.11.1",
    title: "Procedimiento de Adquisición de Bienes y Servicios",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 1,
    description: "Establecer criterios de SST para la adquisición o arrendamiento de bienes y contratación de servicios.",
    minGroup: 60,
  },
  {
    code: "3.1.3",
    title: "Perfil Sociodemográfico y Morbilidad de la Población Trabajadora",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 0,
    weight60: 1,
    description: "Mantener actualizado el perfil sociodemográfico y diagnóstico de condiciones de salud de los trabajadores.",
    minGroup: 60,
  },
  {
    code: "3.1.5",
    title: "Restricciones y Recomendaciones Médico-Laborales",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 1,
    description: "Acatar y dar seguimiento formal a las recomendaciones y restricciones emitidas por la EPS, ARL o médico laboral.",
    minGroup: 60,
  },
  {
    code: "3.1.6",
    title: "Estilos de Vida y Entornos de Trabajo Saludables",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 1,
    description: "Desarrollar actividades de prevención del tabaquismo, alcoholismo, farmacodependencia y fomento de vida activa.",
    minGroup: 60,
  },
  {
    code: "3.1.7",
    title: "Servicios de Higiene y Suministro de Agua Potable",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 1,
    description: "Disponer de agua potable, servicios sanitarios higiénicos y mecanismos adecuados para disposición de residuos.",
    minGroup: 60,
  },
  {
    code: "3.2.1",
    title: "Sistemas de Vigilancia Epidemiológica Ocupacional",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 2.5,
    description: "Implementar programas de vigilancia epidemiológica para los riesgos prioritarios identificados (biomecánico, ruido, químico, etc.).",
    minGroup: 60,
  },
  {
    code: "4.1.1",
    title: "Metodología Formal para Identificación de Peligros (GTC 45)",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 0,
    weight60: 4,
    description: "Aplicar sistemáticamente la Guía Técnica Colombiana GTC 45 para la identificación de peligros y valoración de riesgos.",
    minGroup: 60,
  },
  {
    code: "4.1.3",
    title: "Identificación de Sustancias Catalogadas como Cancerígenas o con Toxicidad Aguda",
    cyclePhase: "PLANEAR",
    weight7: 0,
    weight21: 0,
    weight60: 3,
    description: "Identificar y priorizar medidas de sustitución o control estricto para sustancias químicas cancerígenas o de alta toxicidad.",
    minGroup: 60,
  },
  {
    code: "4.1.4",
    title: "Mediciones Ambientales de Higiene Ocupacional",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 4,
    description: "Realizar mediciones cuantitativas de contaminantes físicos, químicos o biológicos en los puestos de trabajo críticos.",
    minGroup: 60,
  },
  {
    code: "4.2.2",
    title: "Inspecciones Periódicas de Seguridad a Instalaciones y Equipos",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 2.5,
    description: "Ejecutar y documentar inspecciones periódicas a áreas, máquinas, herramientas y equipos con participación del COPASST.",
    minGroup: 60,
  },
  {
    code: "4.2.4",
    title: "Mantenimiento Periódico de Instalaciones, Equipos y Herramientas",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 2.5,
    description: "Garantizar el mantenimiento preventivo y correctivo de infraestructura, maquinaria, vehículos y sistemas de emergencia.",
    minGroup: 60,
  },
  {
    code: "4.2.5",
    title: "Entrega y Reposición de Elementos de Protección Personal (EPP)",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 2.5,
    description: "Suministrar EPP acordes a los peligros, capacitar en su uso y mantener registros individuales firmados de entrega.",
    minGroup: 60,
  },
  {
    code: "5.1.1",
    title: "Conformación y Dotación de la Brigada de Emergencias",
    cyclePhase: "HACER",
    weight7: 0,
    weight21: 0,
    weight60: 5,
    description: "Conformar, capacitar y dotar la brigada de emergencias (primeros auxilios, contraincendios y evacuación) con simulacro anual.",
    minGroup: 60,
  },
  {
    code: "6.1.2",
    title: "Investigación de Accidentes Graves y Mortales según Resolución 1401",
    cyclePhase: "VERIFICAR",
    weight7: 0,
    weight21: 0,
    weight60: 2,
    description: "Remitir el informe de investigación a la ARL y Dirección Territorial del MinTrabajo en un plazo máximo de 15 días hábiles.",
    minGroup: 60,
  },
  {
    code: "6.1.3",
    title: "Medición y Registro de Indicadores Mínimos del SG-SST",
    cyclePhase: "VERIFICAR",
    weight7: 0,
    weight21: 0,
    weight60: 1.25,
    description: "Calcular y analizar semestralmente indicadores de frecuencia, severidad, mortalidad, prevalencia e incidencia de AT/EL.",
    minGroup: 60,
  },
  {
    code: "6.1.4",
    title: "Auditoría Anual del SG-SST con Alcance a Todos los Estándares",
    cyclePhase: "VERIFICAR",
    weight7: 0,
    weight21: 0,
    weight60: 1.25,
    description: "Planificar y ejecutar al menos una auditoría anual interna o externa independiente sobre el cumplimiento del SG-SST.",
    minGroup: 60,
  },
  {
    code: "6.1.5",
    title: "Revisión Anual por la Alta Dirección",
    cyclePhase: "VERIFICAR",
    weight7: 0,
    weight21: 0,
    weight60: 1.25,
    description: "Revisar anualmente el sistema por la gerencia general para evaluar su eficacia y definir recursos y directrices.",
    minGroup: 60,
  },
  {
    code: "7.1.1",
    title: "Plan de Mejoramiento Derivado de la Autoevaluación y Auditorías",
    cyclePhase: "ACTUAR",
    weight7: 0,
    weight21: 0,
    weight60: 2.5,
    description: "Formular planes de mejoramiento continuo inmediatos con acciones preventivas y correctivas basadas en los hallazgos.",
    minGroup: 60,
  },
  {
    code: "7.1.2",
    title: "Acciones Preventivas y Correctivas Implementadas",
    cyclePhase: "ACTUAR",
    weight7: 0,
    weight21: 0,
    weight60: 2.5,
    description: "Cerrar eficazmente las no conformidades y oportunidades de mejora identificadas en inspecciones, auditorías y accidentes.",
    minGroup: 60,
  }
];

/**
 * Determina el número de estándares obligatorios según Resolución 0312 de 2019:
 * - Grupo 1: <= 10 trabajadores y ARL I, II, III -> 7 estándares
 * - Grupo 2: 11 a 50 trabajadores y ARL I, II, III -> 21 estándares
 * - Grupo 3: > 50 trabajadores O cualquier empresa con ARL IV o V -> 60 estándares
 */
export function calculateRequiredStandards(workerCount: number, arlRiskLevel: number): 7 | 21 | 60 {
  if (arlRiskLevel >= 4) {
    return 60; // Riesgo IV o V siempre son 60 estándares sin importar trabajadores
  }
  if (workerCount <= 10) {
    return 7;
  }
  if (workerCount <= 50) {
    return 21;
  }
  return 60;
}

export function getStandardsForGroup(group: 7 | 21 | 60): StandardItem[] {
  if (group === 7) {
    return RESOLUCION_0312_STANDARDS.filter((s) => s.minGroup === 7);
  }
  if (group === 21) {
    return RESOLUCION_0312_STANDARDS.filter((s) => s.minGroup === 7 || s.minGroup === 21);
  }
  return RESOLUCION_0312_STANDARDS;
}
